let Order_size = 100;
let Order_precision = {
  TRXBUSD: 0,
  XEMUSDT: 0,
  LTCUSDT: 3,
  SUIUSDT: 1,
  DODOXUSDT: 0,
  MKRUSDT: 3,
  QNTUSDT: 1,
  ETHBTC: 2,
  BANDUSDT: 1,
  TOMOUSDT: 0,
  ARBUSDT: 1,
  XLMUSDT: 0,
  BLZUSDT: 0,
  CRVUSDT: 1,
  AUDIOUSDT: 0,
  STMXUSDT: 0,
  BTCUSDT: 3,
  SANDBUSD: 1,
  PENDLEUSDT: 0,
  FXSUSDT: 1,
  ANTUSDT: 1,
  MTLUSDT: 0,
  HOTUSDT: 0,
  CVXUSDT: 0,
  FILBUSD: 1,
  MAVUSDT: 0,
  MAGICUSDT: 1,
  GRTUSDT: 0,
  ADABUSD: 0,
  NEARUSDT: 0,
  RADUSDT: 0,
  ARKMUSDT: 0,
  AGLDUSDT: 0,
  ONEUSDT: 0,
  THETAUSDT: 1,
  CVXBUSD: 1,
  DENTUSDT: 0,
  XTZUSDT: 1,
  STORJUSDT: 0,
  OGNUSDT: 0,
  QTUMUSDT: 1,
  OCEANUSDT: 0,
  DOTUSDT: 1,
  LPTUSDT: 1,
  ROSEUSDT: 0,
  WOOUSDT: 0,
  SKLUSDT: 0,
  DYDXUSDT: 1,
  IDEXUSDT: 0,
  ETHUSDT: 3,
  SXPUSDT: 1,
  JASMYUSDT: 0,
  RDNTUSDT: 0,
  FTTUSDT: 1,
  MATICUSDT: 0,
  KEYUSDT: 0,
  ETCUSDT: 2,
  WAVESBUSD: 1,
  LUNA2USDT: 0,
  BATUSDT: 1,
  HNTUSDT: 0,
  TLMBUSD: 0,
  RUNEUSDT: 0,
  OMGUSDT: 1,
  EGLDUSDT: 1,
  NEARBUSD: 1,
  NMRUSDT: 1,
  RVNUSDT: 0,
  "1000PEPEUSDT": 0,
  TRBUSDT: 1,
  LTCBUSD: 2,
  UNFIUSDT: 1,
  DARUSDT: 1,
  "1000LUNCBUSD": 0,
  XVSUSDT: 1,
  CTKUSDT: 0,
  BNBUSDT: 2,
  MANAUSDT: 0,
  DEFIUSDT: 3,
  ENJUSDT: 0,
  FLMUSDT: 0,
  DGBUSDT: 0,
  ZENUSDT: 1,
  ICXUSDT: 0,
  SUSHIUSDT: 0,
  IMXUSDT: 0,
  CFXUSDT: 0,
  GALBUSD: 0,
  ETHBUSD: 3,
  MATICBUSD: 0,
  VETUSDT: 0,
  SHIBUSDT: 0,
  AUCTIONBUSD: 1,
  HOOKUSDT: 1,
  CHZUSDT: 0,
  REEFUSDT: 0,
  KNCUSDT: 0,
  GMTUSDT: 0,
  FLOKIUSDT: 0,
  RSRUSDT: 0,
  BTSUSDT: 0,
  BNTUSDT: 0,
  APTBUSD: 1,
  IOSTUSDT: 0,
  APEUSDT: 0,
  DOGEUSDT: 0,
  "1000SHIBBUSD": 0,
  LDOBUSD: 1,
  ENSUSDT: 1,
  CTSIUSDT: 0,
  TRXUSDT: 0,
  USDCUSDT: 0,
  DASHUSDT: 3,
  STXUSDT: 0,
  DUSKUSDT: 0,
  "1INCHUSDT": 0,
  PEOPLEUSDT: 0,
  HBARUSDT: 0,
  UMAUSDT: 0,
  JOEUSDT: 0,
  BLURUSDT: 0,
  AVAXUSDT: 0,
  SRMUSDT: 0,
  IOTXUSDT: 0,
  ADAUSDT: 0,
  RENUSDT: 0,
  BNXUSDT: 1,
  AGIXBUSD: 0,
  YFIUSDT: 3,
  ANKRUSDT: 0,
  ARUSDT: 1,
  HIGHUSDT: 1,
  RNDRUSDT: 1,
  PERPUSDT: 1,
  SNXUSDT: 1,
  FTTBUSD: 1,
  DODOBUSD: 0,
  LEVERUSDT: 0,
  GTCUSDT: 1,
  AGIXUSDT: 0,
  FTMUSDT: 0,
  GALUSDT: 0,
  GALAUSDT: 0,
  API3USDT: 1,
  SOLBUSD: 0,
  COCOSUSDT: 1,
  BTCSTUSDT: 1,
  ALICEUSDT: 1,
  CELOUSDT: 1,
  ATAUSDT: 0,
  DOGEBUSD: 0,
  CKBUSDT: 0,
  PHBBUSD: 0,
  XVGUSDT: 0,
  KSMUSDT: 1,
  STGUSDT: 0,
  APEBUSD: 1,
  COMPUSDT: 3,
  ALGOUSDT: 1,
  ICPUSDT: 0,
  BCHUSDT: 3,
  GMXUSDT: 2,
  LINAUSDT: 0,
  YGGUSDT: 0,
  EDUUSDT: 0,
  AXSUSDT: 0,
  UNIUSDT: 0,
  MASKUSDT: 0,
  BTCDOMUSDT: 3,
  C98USDT: 0,
  GALABUSD: 0,
  FOOTBALLUSDT: 2,
  CVCUSDT: 0,
  OXTUSDT: 0,
  OPUSDT: 1,
  BLUEBIRDUSDT: 1,
  COTIUSDT: 0,
  SFPUSDT: 0,
  SCUSDT: 0,
  TRUUSDT: 0,
  ETHUSDT_230929: 3,
  TLMUSDT: 0,
  SOLUSDT: 0,
  FILUSDT: 1,
  MINAUSDT: 0,
  EOSUSDT: 1,
  BNBBUSD: 2,
  LDOUSDT: 0,
  XMRUSDT: 3,
  XRPBUSD: 1,
  LQTYUSDT: 1,
  ATOMUSDT: 2,
  ONTUSDT: 1,
  XRPUSDT: 1,
  BALUSDT: 1,
  GMTBUSD: 1,
  BTCBUSD: 3,
  AMBUSDT: 0,
  WAVESUSDT: 1,
  SSVUSDT: 2,
  UNIBUSD: 1,
  MDTUSDT: 0,
  BELUSDT: 0,
  ZRXUSDT: 1,
  LEVERBUSD: 0,
  COMBOUSDT: 1,
  TUSDT: 0,
  ETCBUSD: 1,
  KAVAUSDT: 1,
  AVAXBUSD: 1,
  LINKBUSD: 1,
  HFTUSDT: 0,
  CHRUSDT: 0,
  CELRUSDT: 0,
  SPELLUSDT: 0,
  FETUSDT: 0,
  AMBBUSD: 0,
  IOTAUSDT: 1,
  ANCBUSD: 0,
  RAYUSDT: 1,
  LITUSDT: 1,
  NEOUSDT: 2,
  PHBUSDT: 0,
  WLDUSDT: 0,
  ZECUSDT: 3,
  LINKUSDT: 2,
  NKNUSDT: 0,
  INJUSDT: 1,
  KLAYUSDT: 1,
  AAVEUSDT: 1,
  "1000XECUSDT": 0,
  ARPAUSDT: 0,
  DOTBUSD: 1,
  BAKEUSDT: 0,
  ZILUSDT: 0,
  FTMBUSD: 0,
  ALPHAUSDT: 0,
  SANDUSDT: 0,
  APTUSDT: 1,
  "1000LUNCUSDT": 0,
  BTCUSDT_230929: 3,
  RLCUSDT: 1,
  LRCUSDT: 0,
  IDUSDT: 0,
  ACHUSDT: 0,
  FLOWUSDT: 1,
  ASTRUSDT: 0,
};

console.log("ORDR_MANAGER");

let Price_precision = {
  APTUSDT: 3,
  TRXUSDT: 5,
  LTCUSDT: 2,
  DOTUSDT: 3,
  ADAUSDT: 4,
  ETHUSDT: 2,
  BTCUSDT: 2,
  LINKUSDT: 3,
  NEARUSDT: 3,
  AVAXUDT: 3,
  BCHUSDT: 2,
  FILUSDT: 3,
  RUNEUSDT: 3,
  DYDXUSDT: 3,
  HBARUSDT: 5,
  XRPUSDT: 4,
  MATICUSDT: 4,
};

// let Price_precision = {
//   ARKMUSDT: 7,
//   RVNUSDT: 5,
//   BTCUSDT: 2,
//   ZILUSDT: 5,
//   BNBBUSD: 3,
//   CHZUSDT: 5,
//   ARUSDT: 3,
//   TRXBUSD: 7,
//   AGIXBUSD: 7,
//   NKNUSDT: 5,
//   PHBUSDT: 7,
//   WOOUSDT: 5,
//   AMBUSDT: 7,
//   TRUUSDT: 7,
//   EGLDUSDT: 3,
//   NEARBUSD: 7,
//   RLCUSDT: 4,
//   CVXBUSD: 7,
//   SCUSDT: 6,
//   WAVESBUSD: 7,
//   IDUSDT: 7,
//   SUIUSDT: 6,
//   KEYUSDT: 7,
//   ALICEUSDT: 3,
//   KNCUSDT: 5,
//   SRMUSDT: 4,
//   JOEUSDT: 7,
//   FLOWUSDT: 3,
//   TRBUSDT: 3,
//   FTTBUSD: 3,
//   IOTAUSDT: 4,
//   MINAUSDT: 7,
//   LEVERUSDT: 7,
//   GMXUSDT: 6,
//   UNFIUSDT: 3,
//   GMTUSDT: 5,
//   AGIXUSDT: 7,
//   ETHUSDT_231229: 2,
//   PHBBUSD: 7,
//   SEIUSDT: 7,
//   GRTUSDT: 5,
//   BELUSDT: 5,
//   FTMBUSD: 7,
//   EDUUSDT: 7,
//   HIGHUSDT: 6,
//   SANDUSDT: 5,
//   ICXUSDT: 4,
//   RSRUSDT: 6,
//   LINAUSDT: 5,
//   COMPUSDT: 2,
//   MKRUSDT: 2,
//   BTCSTUSDT: 3,
//   QNTUSDT: 6,
//   ETHBUSD: 2,
//   LDOBUSD: 6,
//   XVSUSDT: 6,
//   TUSDT: 7,
//   LPTUSDT: 3,
//   BTSUSDT: 5,
//   DOTBUSD: 7,
//   HOTUSDT: 6,
//   IOTXUSDT: 5,
//   BTCBUSD: 1,
//   PENDLEUSDT: 7,
//   NEOUSDT: 3,
//   UNIUSDT: 4,
//   YGGUSDT: 7,
//   LEVERBUSD: 7,
//   KLAYUSDT: 4,
//   ADAUSDT: 5,
//   COCOSUSDT: 6,
//   AGLDUSDT: 7,
//   BTCUSDT_230929: 1,
//   BANDUSDT: 4,
//   OXTUSDT: 7,
//   CVCUSDT: 5,
//   SXPUSDT: 4,
//   SOLBUSD: 4,
//   UMAUSDT: 6,
//   RAYUSDT: 3,
//   LINKUSDT: 3,
//   BNXUSDT: 6,
//   ALPHAUSDT: 5,
//   FLMUSDT: 4,
//   AUDIOUSDT: 4,
//   FOOTBALLUSDT: 5,
//   ANKRUSDT: 6,
//   DYDXUSDT: 3,
//   ASTRUSDT: 7,
//   ACHUSDT: 7,
//   PERPUSDT: 6,
//   ZRXUSDT: 4,
//   SOLUSDT: 4,
//   LITUSDT: 3,
//   KSMUSDT: 3,
//   XVGUSDT: 7,
//   ANCBUSD: 7,
//   SNXUSDT: 3,
//   ARPAUSDT: 5,
//   HBARUSDT: 5,
//   WLDUSDT: 7,
//   FILBUSD: 7,
//   ONEUSDT: 5,
//   STGUSDT: 7,
//   MAVUSDT: 7,
//   TRXUSDT: 5,
//   XLMUSDT: 5,
//   REEFUSDT: 6,
//   LUNA2USDT: 7,
//   "1000FLOKIUSDT": 7,
//   MTLUSDT: 4,
//   ENJUSDT: 5,
//   ETHUSDT: 2,
//   BTCDOMUSDT: 1,
//   APTUSDT: 5,
//   "1000LUNCUSDT": 7,
//   "1INCHUSDT": 4,
//   OMGUSDT: 4,
//   DARUSDT: 4,
//   HNTUSDT: 4,
//   XRPBUSD: 4,
//   BNTUSDT: 7,
//   DUSKUSDT: 5,
//   BLURUSDT: 7,
//   RUNEUSDT: 4,
//   YFIUSDT: 1,
//   USDCUSDT: 7,
//   SUSHIUSDT: 4,
//   CFXUSDT: 7,
//   IMXUSDT: 4,
//   AUCTIONBUSD: 7,
//   MATICBUSD: 7,
//   GALABUSD: 7,
//   RADUSDT: 6,
//   ANTUSDT: 3,
//   BLUEBIRDUSDT: 5,
//   MANAUSDT: 4,
//   LINKBUSD: 7,
//   FILUSDT: 3,
//   AVAXBUSD: 6,
//   GALBUSD: 7,
//   JASMYUSDT: 6,
//   STXUSDT: 7,
//   OCEANUSDT: 5,
//   FTTUSDT: 4,
//   ZENUSDT: 3,
//   "1000XECUSDT": 5,
//   IDEXUSDT: 7,
//   RNDRUSDT: 6,
//   FETUSDT: 7,
//   ONTUSDT: 4,
//   ARBUSDT: 6,
//   KAVAUSDT: 4,
//   GMTBUSD: 7,
//   DASHUSDT: 2,
//   XTZUSDT: 3,
//   ATAUSDT: 4,
//   "1000LUNCBUSD": 7,
//   OPUSDT: 7,
//   ICPUSDT: 6,
//   NMRUSDT: 6,
//   SKLUSDT: 5,
//   OGNUSDT: 4,
//   AVAXUSDT: 4,
//   LRCUSDT: 5,
//   BAKEUSDT: 4,
//   LDOUSDT: 6,
//   ATOMUSDT: 3,
//   XEMUSDT: 4,
//   WAVESUSDT: 4,
//   CELOUSDT: 3,
//   TOMOUSDT: 4,
//   AMBBUSD: 7,
//   ROSEUSDT: 5,
//   GALAUSDT: 5,
//   SSVUSDT: 6,
//   APTBUSD: 5,
//   GTCUSDT: 3,
//   BCHUSDT: 2,
//   LQTYUSDT: 6,
//   RENUSDT: 5,
//   DODOXUSDT: 7,
//   BNBUSDT: 3,
//   TLMBUSD: 7,
//   XRPUSDT: 4,
//   XMRUSDT: 2,
//   STMXUSDT: 5,
//   LTCBUSD: 6,
//   BTCUSDT_231229: 1,
//   DOTUSDT: 3,
//   DEFIUSDT: 1,
//   RDNTUSDT: 7,
//   INJUSDT: 6,
//   COMBOUSDT: 6,
//   CYBERUSDT: 6,
//   ENSUSDT: 3,
//   IOSTUSDT: 6,
//   PEOPLEUSDT: 5,
//   THETAUSDT: 4,
//   DOGEUSDT: 6,
//   ETCBUSD: 6,
//   BATUSDT: 4,
//   "1000SHIBUSDT": 6,
//   ADABUSD: 5,
//   MASKUSDT: 4,
//   CTKUSDT: 5,
//   GALUSDT: 5,
//   MAGICUSDT: 6,
//   DENTUSDT: 6,
//   AXSUSDT: 5,
//   STORJUSDT: 4,
//   ETCUSDT: 3,
//   CHRUSDT: 4,
//   CVXUSDT: 6,
//   LTCUSDT: 2,
//   TLMUSDT: 7,
//   EOSUSDT: 3,
//   FTMUSDT: 6,
//   SFPUSDT: 4,
//   "1000PEPEUSDT": 7,
//   ETHBTC: 6,
//   CRVUSDT: 3,
//   HFTUSDT: 7,
//   VETUSDT: 6,
//   COTIUSDT: 5,
//   NEARUSDT: 4,
//   API3USDT: 4,
//   AAVEUSDT: 3,
//   DODOBUSD: 7,
//   SANDBUSD: 7,
//   FXSUSDT: 6,
//   "1000SHIBBUSD": 7,
//   ZECUSDT: 2,
//   DGBUSDT: 5,
//   MDTUSDT: 7,
//   BLZUSDT: 5,
//   QTUMUSDT: 3,
//   DOGEBUSD: 6,
//   APEUSDT: 4,
//   HOOKUSDT: 6,
//   SPELLUSDT: 7,
//   CELRUSDT: 5,
//   CKBUSDT: 7,
//   APEBUSD: 7,
//   UNIBUSD: 6,
//   ALGOUSDT: 4,
//   BALUSDT: 3,
//   CTSIUSDT: 4,
//   C98USDT: 4,
//   ETHUSDT_230929: 2,
//   MATICUSDT: 5,
// };

async function getPositions(binance) {
  let Positions = await binance.futuresAccount();
  let Active_postitions = [];
  Object.keys(Positions).forEach((key) => {
    // console.log("key", Positions);
    if (key == "positions") {
      Positions[key].forEach((position) => {
        if (position.initialMargin > 0) {
          Active_postitions.push(position.symbol);
        }
      });
    }
  });

  return Active_postitions;
}

export async function placeOrder(binance, symbol, order_to_place, cb, cb_err) {
  try {
    let symbol_price = await binance.futuresMarkPrice(symbol);

    let Order_quantity = Order_size / symbol_price.markPrice;
    Order_quantity = Order_quantity.toFixed(Order_precision[symbol]);
    let Order = null;
    let TP_order = null;
    let All_positions = await getPositions(binance);

    if (!All_positions.includes(symbol)) {
      if (order_to_place.entrySignal == "BullTAR") {
        // await binance.futuresSell(symbol, Order_quantity, 3700, {
        //   timeInForce: "GTC",
        //   stopPrice: 3700,
        //   type: "STOP",
        // });

        Order = await binance.futuresMarketBuy(symbol, Order_quantity, {
          recvWindow: 8000,
        });

        TP_order = await binance.futuresSell(
          symbol,
          Order_quantity,
          (+symbol_price.markPrice * 1.004).toFixed(Price_precision[symbol])
        );
      } else {
        Order = await binance.futuresMarketSell(symbol, Order_quantity, {
          recvWindow: 8000,
        });
        TP_order = await binance.futuresBuy(
          symbol,
          Order_quantity,
          (+symbol_price.markPrice * 0.996).toFixed(Price_precision[symbol])
        );
      }
    }
    console.log("AAAAAAAAAAA", TP_order, Order);

    let output = {
      id: order_to_place.id,
      symbol,
      open_price: symbol_price.markPrice,
      quantity: Order_quantity,
    };
    if (Order && Order.status == "NEW") {
      output.open_time = Order.updateTime;
      output.side = Order.side;
      cb(output);
    } else {
      throw new Error("Order not opened");
    }
  } catch (err) {
    cb_err(err.message);
  }
}

export async function closeOrder(binance, symbol, order_to_close, cb, cb_err) {
  try {
    let symbol_price = await binance.futuresMarkPrice(symbol);
    let Order = null;
    if (order_to_close.side == "SELL") {
      Order = await binance.futuresMarketBuy(symbol, order_to_close.quantity, {
        recvWindow: 8000,
      });
    } else {
      Order = await binance.futuresMarketSell(symbol, order_to_close.quantity, {
        recvWindow: 8000,
      });
    }

    if (Order && Order.status == "NEW") {
      order_to_close.close_price = symbol_price.markPrice;
      order_to_close.close_time = Order.updateTime;
      order_to_close.isClosed = true;
      cb(order_to_close);
    } else {
      order_to_close.isClosed = false;
      cb_err("Order not closed");
    }
  } catch (err) {
    cb_err(err);
  }
}

//ORDER RETURN EXAMPLE
// {
//     orderId: 39388066578,
//     symbol: 'XRPUSDT',
//     status: 'NEW',
//     clientOrderId: '8bAELhf4uWkbCwbkUIYsF6',
//     price: '0.0000',
//     avgPrice: '0.00',
//     origQty: '8.0',
//     executedQty: '0.0',
//     cumQty: '0.0',
//     cumQuote: '0.00000',
//     timeInForce: 'GTC',
//     type: 'MARKET',
//     reduceOnly: false,
//     closePosition: false,
//     side: 'BUY',
//     positionSide: 'BOTH',
//     stopPrice: '0.0000',
//     workingType: 'CONTRACT_PRICE',
//     priceProtect: false,
//     origType: 'MARKET',
//     updateTime: 1692040066868
//   }
